### ISSUE TITLE
Can’t find the jar file of  jena-kb and code-gen 

### ISSUE THREAD

**Issue by reio-k** [william-vw/glean#1]
Hi, Thank you to share this great source code! 
I try to install this project using maven, but can’t find the jar file of  jena-kb and code-gen belonging to wvw.semweb.
Could you share these jar files?

Thank you very much.

**Comment by william-vw** [comment]
@reio-k Thanks for catching this. 6f9c422825ee7b1459401685e40329d595487be2 adds the `jena-kb` project, and `jen3` as a submodule. The `code-gen` project is quite experimental so I removed the code referencing it from `glean-core`. Just let me know whether that solves your problem - this is work in progress so other things may not be setup properly.

**Comment by reio-k** [comment]
@william-vw Thank you so much for your very quick revision!
Now I confirm that it works well with installing and able to show “Hello World!” on tomcat server!
The web app of “Dyslipidemia CKD Workflow” is also pretty awesome!!

Thank you very much again!
